### ISSUE TITLE
does this plugin work yet?

### ISSUE THREAD

**Issue by justinmulwee** [kalebheitzman/grav-plugin-events#1]
Hi. This isn't exactly a bug, but this seemed like the best place to ask. I went to install this plugin with bin/gpm but got `Nothing to install`. Then I looked and realized you just published it yesterday so maybe it's not even finished, much less in the plugin directory.

But I'm looking for something to allow a non-developer client to easily create and delete events from grav admin, which would then populate an events page. Is that what this plugin is? And if so, is it usable yet?

Thanks.

**Comment by kalebheitzman** [comment]
I just released the first version 2 minutes ago. You can clone it into your plugins folder under events and it should work.

**Comment by kalebheitzman** [comment]
Let me know if you need any assistance. Be sure to copy the yaml blueprint files over to your theme if you use the admin plugin.

**Comment by justinmulwee** [comment]
Sweet, it works exactly as expected. Thanks. Feel free to close/delete this issue to declutter your repo.

If you had any doubts about this being useful to someone else, me finding your repo on day 1 should be your answer.

**Comment by kalebheitzman** [comment]
Ha ha thanks.
