### ISSUE TITLE
Breakdown menu in antimatter list also coming generated events

### ISSUE THREAD

**Issue by nsteinmetz** [kalebheitzman/grav-plugin-events#10]
Hi,

So i assigned the `event` page type to a test page named "Presentation". Now, with menu, I see this page and all the coming events (which I would like to avoid). Is it a bug ? How can I fifter out the generated events from my menu ?

What I have when I'm on the "Presentation page":

![bug-events](https://cloud.githubusercontent.com/assets/33180/13906843/1d025df8-eee1-11e5-8b4c-447c7dcc402e.png)

What I have when I click on an event (ie link to given event, http://localhost:8080/le-club/presentation/evt:73b402 and the original content is still as 1st result)):

![bug-events2 2](https://cloud.githubusercontent.com/assets/33180/13906892/013be2fa-eee2-11e5-9643-e84f610ab26f.png)

If I'm on a non event content, rendering is:

![bug-events3](https://cloud.githubusercontent.com/assets/33180/13906886/dd74c2ec-eee1-11e5-9594-0e2ac1b5f772.png)

**Comment by kalebheitzman** [comment]
Something like this is generally theme specific. I'll add an option in the admin blueprint that hides this from menus automatically but that can be disabled if someone wants it in a menu for some reason.

**Comment by nsteinmetz** [comment]
Hi @kalebheitzman,

Thanks for the reply ; as I just start with Grav, could you tell me what kind of filter I could use to exclude the generated events (not the initial one) from the menu ? A link to the doc should be sufficient

**Comment by nsteinmetz** [comment]
Hi @kalebheitzman,

Thanks for the reply ; as I just start with Grav, could you tell me what kind of filter I could use to exclude the generated events (not the initial one) from the menu ? A link to the doc and the key on which I should filter should be sufficient.

Thanks !

**Comment by kalebheitzman** [comment]
There isn't currently a way to exclude generated events. I'll have to code something for this behavior.

**Comment by nsteinmetz** [comment]
Ok,thanks ! Let me know once I can test it.

**Comment by nsteinmetz** [comment]
Hi @kalebheitzman 

I want to display latest events on my home page and I still have the issue. How could I fix the issue or have a workaround ?

Why don't you have the issue when using a collection like for the events or agenda page but when using `page.find()` we have the issue ?

Thanks,
Nicolas

**Comment by kalebheitzman** [comment]
@nsteinmetz i think this has something to do with the way Im generating events. Instead of polluting the pages collection I'm storing events in a array where each event is duplicated x number of times with corrected dates etc. I'm doing some heavy development with this plugin at the moment and I'll see if I can look into as I go.

**Comment by kalebheitzman** [comment]
I've done some heavy development on the plugin the last couple of months. The way events are processed is completely different now. This may or may not be an issue anymore. I'm going to close the issue, but if it does end up happening again, just open a new issue. Using page functions like .find() and .eval() should work just fine now. Check the templates to see code in use.
