### ISSUE TITLE
Admin Event Creation

### ISSUE THREAD

**Issue by Vivalldi** [kalebheitzman/grav-plugin-events#11]
Just wanted to suggest that creating events via admin would be awesome.  Grav now supports blueprints extensions so it may be possible to add on to existing page editing and add options to edit event.

If I have the time I might create a pull request

**Comment by kalebheitzman** [comment]
This is already a part of the events plugin. At the moment you need to copy over the relevant blueprints files. The Grav team is currently working on Blueprint updates so that this won't be an issue in the future. Just copy over the blueprint files to your theme.

**Comment by kalebheitzman** [comment]
I don't know when that particular feature is supposed to be released.

**Comment by Vivalldi** [comment]
As soon as you said that I realized that the project I usually run uses the new changes from github while this project in question uses the releases. Sorry about that.

And that feature is coming soon
the `feature/blueprints` branch will be merged in soon

**Comment by kalebheitzman** [comment]
@Vivalldi are there any examples of this functionality so I can add it to the plugin?

**Comment by kalebheitzman** [comment]
Fixed with Issue #21
