### ISSUE TITLE
Calendar is displaying the start and end date wrong

### ISSUE THREAD

**Issue by muuvmuuv** [kalebheitzman/grav-plugin-events#12]
Hey,

I set an start and end date for each event. In my calendar is just the start of the event shown and that twice. So it should be like in my apple calendar. Where the event is shown on every day between the start and end date.

Also on every 16th of the month it gives the current day class. That should be just today not the next 16th.

![history calendar](https://cloud.githubusercontent.com/assets/11534760/13914270/86b2dbd0-ef4d-11e5-90c7-79ea096578c8.png)

**Comment by kalebheitzman** [comment]
I haven't coded times into the calendar piece. Is this something you added?

**Comment by muuvmuuv** [comment]
You I also have not much time to go through you code. I tried some things with twig. But that is not really recommend, because the events are stored as an array with the day month year as key instead of only date.

**Comment by kalebheitzman** [comment]
I've fixed the current day issue also referenced in Issue #15. I'll have to look into the other part of this that you're asking about. I'm not sure I fully understand. You want the end times in the calendar?

**Comment by kalebheitzman** [comment]
Actually, I see what you're saying. This issue was resolved a couple of release ago.
