### ISSUE TITLE
http://brandr.grav.co/ down

### ISSUE THREAD

**Issue by COLABORATI** [kalebheitzman/grav-plugin-events#13]
The demo site is down.

**Comment by kalebheitzman** [comment]
Wrong link. It's supposed to be http://grav.brandr.co

**Comment by COLABORATI** [comment]
The wrong link is in the README.md.

**Comment by Sogl** [comment]
Same here...

**Comment by kalebheitzman** [comment]
I've updated the readme to the correct link and it will be visible with the next release.
http://grav.brandr.co

**Comment by kalebheitzman** [comment]
https://grav.brandr.co/calendar/year:2016/month:03

**Comment by Kaepsele** [comment]
The demo site is down again.
