### ISSUE TITLE
Calendar template doesn't check for month when highlighting current day

### ISSUE THREAD

**Issue by brinkofblink** [kalebheitzman/grav-plugin-events#15]
In the calendar template, a current day is shown in each month (eg, on 22 June, the 22 August, September, October etc have the class 'current'.)

Quick fix is to add this before line 54 in calendar.html.twig: `{% set month = "now"|date("F") %}`
and add a check to line 58: `{% if (day == calendar.currentDay) and (month == calendar.date|date("F")) %}`

**Comment by kalebheitzman** [comment]
I've added and tested your contribution. I'll push it with the next release. Thanks!
