### ISSUE TITLE
Update For Grav 1.1?

### ISSUE THREAD

**Issue by Xarcell** [kalebheitzman/grav-plugin-events#16]
I tried installing this on a 1.1 Release Candidate and in said it installed fine, but the site is throwing errors. Any chance for an update on this plugin?

Site with error: http://test-apps.xarcell-studios.com/grav-rc1/grav-admin/

The only other plugin installed is the admin plugin.

**Comment by nsteinmetz** [comment]
Same error but it's a duplicates of https://github.com/kalebheitzman/grav-plugin-datetools/issues/5

**Comment by kalebheitzman** [comment]
I've fixed this issue in my plugin by assigning config to a variable and passing it my plugin class instead of trying to pass the grav object to my class.
