### ISSUE TITLE
Event Post Not Showing

### ISSUE THREAD

**Issue by LieutenantRice** [kalebheitzman/grav-plugin-events#18]
Hey guys, I read through your readme and did as suggested but have had no success with getting an event to show up on my page. I used an example frontmatter from the readme and added new dates to it, and didn't add anything to the page content itself as I couldn't find anything in the readme suggesting I'd need to. Is there something I'm overlooking? Thanks.

URL in question
[http://beta.thehouseofindie.com/events/indie-game-salon](http://beta.thehouseofindie.com/events/indie-game-salon)

Frontmatter in use

> event:
>     title: 'Indie Game Salon'
>     start: '29/06/2016 8:00pm'
>     end: '29/06/2016 12:00am'
>     repeat: W
>     freq: monthly

**Comment by kalebheitzman** [comment]
Did you define a collection for an events page?

**Comment by LieutenantRice** [comment]
I've tested the frontmatter with the collection in the frontmatter as well which also delivers no results. Here it is with a collection added. I updated the site to include that right now as well. Is this correct?

> collection:
>     '@items':
>         '@taxonomy.type': event
> event:
>     title: 'Indie Game Salon'
>     start: '29/06/2016 8:00pm'
>     end: '29/06/2016 12:00am'
>     repeat: W
>     freq: monthly

**Comment by paulcmal** [comment]
You seem to have mixed up the collection and the individual events.

See the difference [here](https://github.com/kalebheitzman/grav-brandr-pages/tree/master/02.events) between the [events.md](https://raw.githubusercontent.com/kalebheitzman/grav-brandr-pages/master/02.events/events.md) to gather a collection of individual events, and the sub-folder [event.md](https://github.com/kalebheitzman/grav-brandr-pages/blob/master/02.events/monthly-retreat/event.md)'s to describe these events.

So each of your events needs "event" frontmatter, but the page collecting event doesn't (as it is not an event but merely a list of pages).

**Comment by kalebheitzman** [comment]
@LieutenantRice any luck with @paulcmal's suggestion?

**Comment by kalebheitzman** [comment]
I believe this issue is just a matter of having everything setup correctly. Closing the issue.

**Comment by LieutenantRice** [comment]
@kalebheitzman 

Sorry for the delayed reply. But no the problem still persists. I've tried using the exact frontmatter with date modifications as suggested in @paulcmal 's post. 

The Event Itself
http://beta.thehouseofindie.com/events/indie-game-salon

> title: 'Indie Game Salon'
> image: igs_header.png
> event:
>     title: 'Indie Game Salon'
>     start: '10/10/2016 8:00pm'
>     end: '10/10/2016 12:00am'
>     repeat: W
>     freq: monthly

The Events Parent Folder (collection)
http://beta.thehouseofindie.com/events

> title: Events
> published: true
> body_classes: 'header-image fullwidth'
> content:
>     items:
>         '@taxonomy':
>             type: event
>     order:
>         by: date
>         dir: asc
>     limit: '10'
>     pagination: true
