### ISSUE TITLE
Issues with internationalizaion

### ISSUE THREAD

**Issue by kimspiess** [kalebheitzman/grav-plugin-events#19]
Hi,

I love your plugin. It spared me lots and lots of time. However, my current project needs to be in German. The dates, however, I only get in English. They need to be German, as well. Where can I change the locale? I couldn't find that in your documentation.

Thanks in advance
Kim

**Comment by paulcmal** [comment]
Hi,

I've implemented multi-language support. You can find the version running it [here](https://github.com/paulcmal/grav-plugin-events).

Please note that my changes have not been [reviewed](https://github.com/kalebheitzman/grav-plugin-events/pull/20) by the original. But I believe them to be functional and stable. If you could beta-test it and give me your own opinion on the matter, that would be amazing.

Also, don't hesitate to contribute German to the languages.yaml file :)

Only hours are not translated yet on this new branch (still displays AM/PM).

**Comment by kalebheitzman** [comment]
I've merged this into the development branch. I'll push an update soon.
