### ISSUE TITLE
Changelog format causing problems

### ISSUE THREAD

**Issue by rhukster** [kalebheitzman/grav-plugin-events#2]
By modifying your changelog format, you are actually breaking it on the getgrav.org site.  Changelog should be like this exactly:

```
# v1.0.10
## 02/11/2016

1. [](#new)
    * Added new `Page::contentMeta()` mechanism to store content-level meta data alongside content
    * Added Japanese language translation    
1. [](#improved)
    * Updated some vendor libraries
1. [](#bugfix)
    * Hide `streams` blueprint from Admin plugin
    * Fix translations of languages with `---` in YAML files
```

Yours is looking like this:

![plugins grav 2016-02-28 18-07-00](https://cloud.githubusercontent.com/assets/1084697/13383395/1635aa1c-de46-11e5-9adb-012d41a7b17e.png)

**Comment by kalebheitzman** [comment]
I'll get this updated ASAP

**Comment by rhukster** [comment]
Cool, jut make sure to dod a release after.

**Comment by kalebheitzman** [comment]
I've pushed a new release with updated phpdoc generated documentation along with the fixed [changelog](https://github.com/kalebheitzman/grav-plugin-events/blob/26f6f1b8b17565e216c34b373ce25865fbe9fb9b/CHANGELOG.md). Thanks.
