### ISSUE TITLE
"Invalid argument supplied for foreach()"

### ISSUE THREAD

**Issue by SuwitSaiphan** [kalebheitzman/grav-plugin-events#27]
After upgrade to Grav 1.1.5, I've this problem.
Once I disable this Events Plugin, the problem was gone.
So how we can fix it.
![grav-events plugin](https://cloud.githubusercontent.com/assets/14764191/18414876/ea2926c0-7804-11e6-8f83-e4e2ca448551.PNG)

**Comment by ChrisGitIt** [comment]
Hi all,

same problem here. I looked a little into the classes/events.php. It looks like there is no default event defined. So the variable $this->eventStack will not be filled. I think there needs to be a default page that shows "no events" if there are no events. 

@SuwitSaiphan: Just add a page based on "event Template" and add an event date. => Error resolved.

@kalebheitzman I would like to help and i will see if i find the time to add an additonal "no events" page. Unfortunately i just started with GRAV ... so i think i will take some time to get into it.

Greets,

Chris

**Comment by kalebheitzman** [comment]
This is related to issue #25. Continue the conversation there.
