### ISSUE TITLE
How to contribute translation for this plugin?

### ISSUE THREAD

**Issue by nsteinmetz** [kalebheitzman/grav-plugin-events#28]
Hi,

I would like to translate all the weekly, daily and other terms which are specific to your plugin in French to use your plugin in a clean way.

Is there a reference file in which I can find all labels and manage the translation ? I saw the `languages.yml` file but seems quite incomplete ; so what's the best way to contribute translation to your plugin ?

Thanks,
Nicolas

**Comment by kalebheitzman** [comment]
This is the last thing I'm cleaning up in the plugin before making a major release. Once I have a language file in place that I think is sustainable and scalable I'll notify you so you can create a translation.

**Comment by kalebheitzman** [comment]
At the moment, this needs translated: https://github.com/kalebheitzman/grav-plugin-events/blob/develop/languages.yaml

I also need to find out if the date twig filter automatically translates dates because if it does, that will limit the amount of translation needed.

**Comment by nsteinmetz** [comment]
Ok, cool ! Let me know :)

**Comment by nsteinmetz** [comment]
By the way, a on the fly translation for the current one ; maybe you need to espace the quote for `Aujourd'hui`:

```
fr:
  PLUGIN_EVENTS:
    CALENDAR:
      TODAY: Aujourd'hui
      VIEW_MORE: Détails
    EVENTS:
BUTTON: En savoir plus
```

**Comment by kalebheitzman** [comment]
I'll go ahead and add this translation. Thanks!

**Comment by nsteinmetz** [comment]
Hmm where can I translate in the meantime the "weekly/monthly/..." labels which are not in this file like `event_meta.html.twig`:

```
<li>Repeats {{ page.header.event.freq|capitalize }}</li>
or
<li>on {{ page.header.event.repeatDisplay }}</li>
```

As you can see [there](http://grav.cvsq.fr/agenda/event-2/evt:ce60d9), it's not translated.

**Comment by kalebheitzman** [comment]
I'll get this updated in the templates and add the relevant section in the language file and push it once I finish a few other updates today.
