### ISSUE TITLE
Missing Events

### ISSUE THREAD

**Issue by elproducto** [kalebheitzman/grav-plugin-events#34]
I am testing out this great extension as I am testing Grav.  For some reason events past 12/25/2016 start date do not show up on the page designated as the events page.  I also made sure the extensions setting "Months Out to Display Events" is set to 12.  Are there any additional settings  that I may have missed.

**Comment by ChrisGitIt** [comment]
Had the same issue until i realized my events where not "published" or where not "visible"...

**Comment by elproducto** [comment]
Page is published and visible in the backend, I also checked the boxes next to each item for just in case and events are still not showing up on the events page.  Event does show up when I change the Events page to Calendar view.

**Comment by elproducto** [comment]
With help from Grav Forum I looked at template file events.html.twig.  I saw date ranges where set to +1 in the "get events by taxonomy" section. I updated setting for end date in the date range section from +1 to +12 and now my events are showing.  I was under the impression that this setting was handled by the Events plugin control panel.

**Comment by kalebheitzman** [comment]
With an update I'm pushing in the near future, this will all be driven by the template to keep the plugin minimalistic.
