### ISSUE TITLE
Event plug-in partially broken after GRAV update

### ISSUE THREAD

**Issue by WhiteWolfSix** [kalebheitzman/grav-plugin-events#37]
This is a very strange situation as the GRAV update has partially broken event plug-in. After reversing the update, everything is ok. It doesn't work in parsing the events and displaying them on an event page using events.html.twig.

**Comment by WhiteWolfSix** [comment]
Well, this issue relates to https://github.com/getgrav/grav/issues/1222

**Comment by flaviocopes** [comment]
I am seeing this just fine? Let me know if I don't see what the issue is

![screen shot 2016-12-21 at 18 04 24](https://cloud.githubusercontent.com/assets/11783388/21398522/e87fd01a-c7a7-11e6-9ac7-f009e81aadf6.png)
![screen shot 2016-12-21 at 18 04 20](https://cloud.githubusercontent.com/assets/11783388/21398524/e88a4a90-c7a7-11e6-9c73-a8f116932bd6.png)
![screen shot 2016-12-21 at 18 04 16](https://cloud.githubusercontent.com/assets/11783388/21398523/e884a978-c7a7-11e6-9578-e7cc5a965f53.png)

**Comment by WhiteWolfSix** [comment]
Well, it is the same event occuring each day. Try to display two or three different events. I can display only one event in my page instead of several defined events.

**Comment by flaviocopes** [comment]
No problem:

![screen shot 2016-12-22 at 17 56 27](https://cloud.githubusercontent.com/assets/11783388/21433378/ef896d08-c86f-11e6-8bf3-90a3f1df5eae.png)

Make sure your events respond to the events.html.twig query which is

```twig
{% set events =
    page.collection({
      'items': {
        '@taxonomy': {
          'type': 'event',
        }
      },
      'dateRange': {
        'start': datetools.today|date('m/d/Y'),
        'end': datetools.parseDate('+1 month')|date('m/d/Y')
      },
      'order': {
        'by': 'date',
        'dir': 'asc'
      },
      'limit': 10,
      'pagination': true
    })
%}
```

(I had the dates in the past so I could not see my events initially)

**Comment by WhiteWolfSix** [comment]
Well, I had changed
`        'end': datetools.parseDate('+1 month')|date('m/d/Y')`
to
`        'end': datetools.parseDate('+12 month')|date('m/d/Y')`
to be able to parse more future events but it still does not help to display more than one event for me.

I still can't understand why plug-in works with older gav version while in newer version it doesn't work and nothing has changed in my events settings.

**Comment by kalebheitzman** [comment]
Can you zip up your pages folder and send it to me? I can test it that way or at least where your events are stored?

**Comment by WhiteWolfSix** [comment]
Here they are:
[pages.zip](https://github.com/kalebheitzman/grav-plugin-events/files/670427/pages.zip)

**Comment by flaviocopes** [comment]
I tried and I did not get events at first, but after adding `sk` to the supported languages (since the pages are translated - e.g. event.sk.md), it worked.

**Comment by WhiteWolfSix** [comment]
OK, I got it to work.

**Comment by flaviocopes** [comment]
What was the problem?

**Comment by WhiteWolfSix** [comment]
I was listing events using featured events not by taxonomy.
