### ISSUE TITLE
Events page displays short day codes instead of day name

### ISSUE THREAD

**Issue by mattwoolnough** [kalebheitzman/grav-plugin-events#4]
Events page currently displays:
Weekly on U until April 3, 2025

instead of:
Weekly on Sunday until April 3, 2025

**Comment by kalebheitzman** [comment]
I've started a [feature branch updating the templates.](https://github.com/kalebheitzman/grav-plugin-events/tree/feature/template-updates) These will be merged into the develop branch soon and then into the next release.

**Comment by kalebheitzman** [comment]
[1.0.6](https://github.com/kalebheitzman/grav-plugin-events/releases/tag/1.0.6) has been released fixing template issues and increasing page load times.
