### ISSUE TITLE
admin crash on plugin save

### ISSUE THREAD

**Issue by gigago** [kalebheitzman/grav-plugin-events#5]
admin crashes on save event plugin after installation 1.0.6 update

Whoops \ Exception \ ErrorException (E_RECOVERABLE_ERROR)
COPY
Argument 1 passed to Grav\Common\Data\Blueprint::mergeArrays() must be of the type array, string given, called in /Library/WebServer/Documents/ami/system/src/Grav/Common/Data/Blueprint.php on line 276 and defined

Note: 100% repeatable

**Comment by mattwoolnough** [comment]
I'm also encountering this issue.

**Comment by kalebheitzman** [comment]
Try deleting /users/config/plugins/events.yaml and saving again. This ended up fixing the issue for me. I'm not sure why.

**Comment by gigago** [comment]
Deleting the yaml seemed to help. There's some snag in the deployment scheme?

**Comment by mattwoolnough** [comment]
deleting the file also worked for me.

**Comment by kalebheitzman** [comment]
I'm not sure what's up with this. I can't replicate it. Closing the issue.
