### ISSUE TITLE
spuriously doubled events in event list after update to 1.0.6

### ISSUE THREAD

**Issue by gigago** [kalebheitzman/grav-plugin-events#6]
After updating the event plugin to 1.0.6., about fifteen non-repeating events from a collection are shown with duplicates. Not all items are duplicated. The list is built by iterating over a collection of event pages. The pages themselves appear untouched. The uri's of the duplicates have the form original-event-uri-HEXNUM

Note: this never happened before the update.

**Comment by kalebheitzman** [comment]
Can you try re-saving an event and see what happens? This happened to me when I began developing the plugin. I discovered it was some sort of caching issue.

**Comment by gigago** [comment]
Sorry, no dice. Indeed I find two instances per doubled page in separate cache files and these are created every time. I surmised it might have to do with seeing _page children_ as well as _events_ - however, changing the event taxonomy parameters made no difference.

**Comment by gigago** [comment]
Ok, the issue has been resolved. In the previous version, I couldn't order events by event.date, so I set page.date separately for all events. Apparently, this caused the events to show up twice in my listing after the update. Clearing page.date removes the page instances, just events are left. And ordering still works fine, so that seems to be cleared up.

Only problem I have now is that event.media.images|first does not set the bannerimage.

**Comment by kalebheitzman** [comment]
I'll have a look. I haven't tested anything compared to page date but I can see where it would conflict with the info that event date sets. In the code, the page date is set to the event date on events that are dynamically created (repeating events that don't have a physical file).

**Comment by kalebheitzman** [comment]
Media is now working in the develop branch. I've started an "Antimatter" feature branch. I'm going to make the calendar templates compatible with the Antimatter theme by default using Antimatter's default blog styling. Theme creators will be able to easily override this with their own templates for `calendar.html.twig`, `events.html.twig`, and `event.html.twig`.
