### ISSUE TITLE
Event repeating once a week not rendered correctly

### ISSUE THREAD

**Issue by mattwoolnough** [kalebheitzman/grav-plugin-events#7]
Event expects to be on multiple days. 
displays:
Repeats Weekly , and Sunday Until April 3, 2025
instead of:
Repeats Weekly each Sunday Until April 3, 2025

**Comment by kalebheitzman** [comment]
Does this happen on both the events and single event pages?

**Comment by mattwoolnough** [comment]
yes, on both. 
Can be seen here: https://mermaids.woolnough.com.au/

**Comment by kalebheitzman** [comment]
A fix has been fixed in the [develop branch](https://github.com/kalebheitzman/grav-plugin-events/commit/13699e8f97b4021a5be700e416e4e1f901a82425). I'll push a release after a few more bugfixes.
