### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by prinla** [kalebheitzman/grav-plugin-events#8]
![events-problem](https://cloud.githubusercontent.com/assets/16805582/13784985/c20d22c4-ead1-11e5-9289-0cea7ec5c2d6.JPG)
I installed the plugin on my localhost-site running the latest grav-version with receptar-skeleton. Once installed the event-plugin it gives me an error "Undefined variable: eventPages"... see attachment
Can you help me?

**Comment by kalebheitzman** [comment]
I've pushed a hotfix solving this with v1.0.8. You can install via git or wait until the update hits the Grav site.
