### ISSUE TITLE
Please provide default page integration sample ?

### ISSUE THREAD

**Issue by nsteinmetz** [kalebheitzman/grav-plugin-events#9]
Hi,

Starting with Grav, i'm not yet clear about how I should add your plugins to the default page ; could you please precise it ?

I read docs about blueprint but so far, I'm not clear about how I should manage this.

Thanks in advance,
Nicolas

**Comment by nsteinmetz** [comment]
Ok, understood, to use it with theme antimatter:
- Copy or symlink `user/plugins/events/blueprints/*.yaml`  to `user/temes/antimatter/blueprints/*`
- Clear cache
- Change page type to event/events or calendar + save and you'll the event tab.
- Enjoy :)

**Comment by kalebheitzman** [comment]
There is a gist available in the readme with defaults as well.

**Comment by nsteinmetz** [comment]
If you mean [this gist](https://gist.github.com/kalebheitzman/edef3f0932150bca8a93), it was unclear for me. It's finally the official doc which made me understood, I needed to copy/paste the `blueprints/events.yaml`, `blueprints/event.yaml` and `blueprints/calendar.yaml` to the blueprints folder of my theme.

**Comment by kalebheitzman** [comment]
I'll add more detailed documentation to cover this. Thanks!
